In [5]:
!pip install numpy
!pip install matplotlib
!pip install pandas
!pip install wordcloud
!pip install nltk


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip


In [6]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
from wordcloud import WordCloud, STOPWORDS
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /home/piyush/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /home/piyush/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [8]:
df = pd.read_csv('/home/piyush/Projects/MLOPS/mlops-project/proj2/spam.csv')
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN


In [9]:
df.drop( columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], inplace = True )
#already removed once but again added by mistake, so removing again

In [10]:
df.head()

,v1,v2
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [11]:
df.rename(columns={'v1':'target', 'v2':'text'}, inplace=True)

In [12]:
!pip install scikit-learn

  Using cached scikit_learn-1.8.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
  Using cached scipy-1.17.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.8.0-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (8.9 MB)
Using cached scipy-1.17.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.2 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [scikit-learn] [scikit-learn]

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip


In [13]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['target'] = encoder.fit_transform(df['target'])
df.head()

,target,text
0,0,"Go until jurong point, crazy.. Available only ..."
1,0,Ok lar... Joking wif u oni...
2,1,Free entry in 2 a wkly comp to win FA Cup fina...
3,0,U dun say so early hor... U c already then say...
4,0,"Nah I don't think he goes to usf, he lives aro..."


In [14]:
df.duplicated().sum()

np.int64(403)

In [15]:
len(df)

5572

In [16]:
df = df.drop_duplicates(keep='first')
len(df)

5169

In [22]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /home/piyush/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/piyush/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [26]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /home/piyush/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [27]:
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import string

ps = PorterStemmer()

def transform_text(text):
    text = text.lower()
    # Tokenize into words
    words = nltk.word_tokenize(text)
    y = []
    for i in words:
        if i.isalnum():
            y.append(i)
    words = y[:]
    y.clear()
    for i in words:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)
    words = y[:]
    y.clear()
    for i in words:
        y.append(ps.stem(i))
    return " ".join(y)

In [28]:
transform_text('I am loving this new phone. Its camera is amazing and the battery life is great!')

'love new phone camera amaz batteri life great'

In [29]:
df['transformed_text'] = df['text'].apply(transform_text)
df.head()

,target,text,transformed_text
0,0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,0,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,free entri 2 wkli comp win fa cup final tkt 21...
3,0,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,0,"Nah I don't think he goes to usf, he lives aro...",nah think goe usf live around though


In [30]:
from sklearn.feature_extraction.text import CountVectorizer , TfidfVectorizer
tfid = TfidfVectorizer(max_features=500)

In [31]:
X = tfid.fit_transform(df['transformed_text']).toarray()
y = df['target'].values

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X , y , test_size=0.2, random_state=2)

## model training 

In [34]:
pip install xgboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.7/131.7 MB 11.2 MB/s  0:00:11m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 293.6/293.6 MB 9.2 MB/s  0:00:31m0:00:0100:01m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [xgboost]m1/2 [xgboost]

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [36]:
pip install lightgbm

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 11.1 MB/s  0:00:00eta 0:00:01

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [47]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report , precision_score , recall_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import VotingClassifier

In [48]:
svc = SVC(kernel = 'sigmoid' , gamma = 1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth = 5 , criterion = 'entropy' , random_state = 2)
rfc = RandomForestClassifier(n_estimators = 200 , random_state = 2)
gbc = GradientBoostingClassifier(n_estimators = 200 , random_state = 2)
abc = AdaBoostClassifier(n_estimators = 200 , random_state = 2)
xgb = XGBClassifier(random_state = 2)
lgbm = LGBMClassifier(random_state = 4)
etc = ExtraTreesClassifier(n_estimators = 200 , random_state = 2)
bgc = BaggingClassifier(n_estimators = 200 , random_state = 2)
sc = StackingClassifier(estimators = [('svc' , svc) , ('knc' , knc) , ('mnb' , mnb) , ('dtc' , dtc) , ('rfc' , rfc) , ('gbc' , gbc) , ('abc' , abc) , ('xgb' , xgb) , ('lgbm' , lgbm) , ('etc' , etc) , ('bgc' , bgc)] , final_estimator = LogisticRegression())
vc = VotingClassifier(estimators = [('svc' , svc) , ('knc' , knc) , ('mnb' , mnb) , ('dtc' , dtc) , ('rfc' , rfc) , ('gbc' , gbc) , ('abc' , abc) , ('xgb' , xgb) , ('lgbm' , lgbm) , ('etc' , etc) , ('bgc' , bgc)] , voting = 'hard')


In [49]:
clfs = {
    'SVC' : svc,
    'KNC' : knc,
    'MNB' : mnb,
    'DTC' : dtc,
    'RFC' : rfc,
    'GBC' : gbc,
    'ABC' : abc,
    'XGB' : xgb,
    'LGBM' : lgbm,
    'ETC' : etc,
    'BGC' : bgc,
    'SC' : sc,
    'VC' : vc
}

In [50]:
def train_classifier(clf , X_train , y_train , X_test , y_test):
    clf.fit(X_train , y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test , y_pred)
    precision = precision_score(y_test , y_pred)
    recall = recall_score(y_test , y_pred)
    print("Accuracy : ", accuracy*100)
    print("Precision : ", precision*100)
    print("Recall : ", recall*100)
    print("Confusion Matrix : \n", confusion_matrix(y_test , y_pred))
    print("Classification Report : \n", classification_report(y_test , y_pred))
    return accuracy , precision , recall

In [51]:
accuracy_scores = []
precision_scores = []
recall_scores = []
for name , clf in clfs.items():
    print("for question : ", name)
    accuracy , precision , recall = train_classifier(clf , X_train , y_train , X_test , y_test)
    accuracy_scores.append(accuracy)
    precision_scores.append(precision)
    recall_scores.append(recall)

for question :  SVC
Accuracy :  96.71179883945842
Precision :  93.33333333333333
Recall :  81.15942028985508
Confusion Matrix : 
 [[888   8]
 [ 26 112]]
Classification Report : 
               precision    recall  f1-score   support

           0       0.97      0.99      0.98       896
           1       0.93      0.81      0.87       138

    accuracy                           0.97      1034
   macro avg       0.95      0.90      0.92      1034
weighted avg       0.97      0.97      0.97      1034

for question :  KNC
Accuracy :  92.74661508704062
Precision :  100.0
Recall :  45.65217391304348
Confusion Matrix : 
 [[896   0]
 [ 75  63]]
Classification Report : 
               precision    recall  f1-score   support

           0       0.92      1.00      0.96       896
           1       1.00      0.46      0.63       138

    accuracy                           0.93      1034
   macro avg       0.96      0.73      0.79      1034
weighted avg       0.93      0.93      0.92      1034



/home/piyush/Projects/MLOPS/mlops-project/.venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Accuracy :  97.29206963249516
Precision :  92.3076923076923
Recall :  86.95652173913044
Confusion Matrix : 
 [[886  10]
 [ 18 120]]
Classification Report : 
               precision    recall  f1-score   support

           0       0.98      0.99      0.98       896
           1       0.92      0.87      0.90       138

    accuracy                           0.97      1034
   macro avg       0.95      0.93      0.94      1034
weighted avg       0.97      0.97      0.97      1034

for question :  ETC
Accuracy :  97.38878143133462
Precision :  93.7007874015748
Recall :  86.23188405797102
Confusion Matrix : 
 [[888   8]
 [ 19 119]]
Classification Report : 
               precision    recall  f1-score   support

           0       0.98      0.99      0.99       896
           1       0.94      0.86      0.90       138

    accuracy                           0.97      1034
   macro avg       0.96      0.93      0.94      1034
weighted avg       0.97      0.97      0.97      1034

for questi

/home/piyush/Projects/MLOPS/mlops-project/.venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/piyush/Projects/MLOPS/mlops-project/.venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


[LightGBM] [Info] Number of positive: 412, number of negative: 2896
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003345 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4647
[LightGBM] [Info] Number of data points in the train set: 3308, number of used features: 265
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.124547 -> initscore=-1.950062
[LightGBM] [Info] Start training from score -1.950062
[LightGBM] [Info] Number of positive: 412, number of negative: 2896
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003739 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4689
[LightGBM] [Info] Number of data points in the train set: 3308, number of used features: 269
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.124547 -> initscore=-1.950062
[LightGB

/home/piyush/Projects/MLOPS/mlops-project/.venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/piyush/Projects/MLOPS/mlops-project/.venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


[LightGBM] [Info] Number of positive: 412, number of negative: 2896
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003126 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4741
[LightGBM] [Info] Number of data points in the train set: 3308, number of used features: 273
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.124547 -> initscore=-1.950062
[LightGBM] [Info] Start training from score -1.950062


/home/piyush/Projects/MLOPS/mlops-project/.venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/home/piyush/Projects/MLOPS/mlops-project/.venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Accuracy :  97.58220502901354
Precision :  95.19999999999999
Recall :  86.23188405797102
Confusion Matrix : 
 [[890   6]
 [ 19 119]]
Classification Report : 
               precision    recall  f1-score   support

           0       0.98      0.99      0.99       896
           1       0.95      0.86      0.90       138

    accuracy                           0.98      1034
   macro avg       0.97      0.93      0.95      1034
weighted avg       0.98      0.98      0.98      1034

for question :  VC
[LightGBM] [Info] Number of positive: 515, number of negative: 3620
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003736 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6334
[LightGBM] [Info] Number of data points in the train set: 4135, number of used features: 338
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.124547 -> initscore=-1.950062
[LightGBM] [Info] Start training from score -1.950062


/home/piyush/Projects/MLOPS/mlops-project/.venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Accuracy :  97.29206963249516
Precision :  95.08196721311475
Recall :  84.05797101449275
Confusion Matrix : 
 [[890   6]
 [ 22 116]]
Classification Report : 
               precision    recall  f1-score   support

           0       0.98      0.99      0.98       896
           1       0.95      0.84      0.89       138

    accuracy                           0.97      1034
   macro avg       0.96      0.92      0.94      1034
weighted avg       0.97      0.97      0.97      1034

